version: '3.8'

services:
  db:
    image: postgres:14
    container_name: crm-postgres
    restart: always
    environment:
      POSTGRES_USER: crm-user
      POSTGRES_PASSWORD: crm-password
      POSTGRES_DB: light-crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
